### ISSUE TITLE
Where's 'main.exe' file?

### ISSUE THREAD

**Issue by Geokeke** [chinageology/GeoPython#1]
I didn't find the 'main.exe' file in mainpage of GeoPython. Could anyone show me? Thx!

**Comment by cycleuser** [comment]
Sorry for being late on response~ I've been busy revising my paper.
It needs to be download form the links in this file: <https://github.com/chinageology/GeoPython/blob/master/Download.md>

there is A Windows section and two links to download the zip file including the main.exe file with other files need. 
The link of the Windows packed up file is 
https://drive.google.com/open?id=0B299gyAIgmpqWm5iS05PNXUwdjA 
as the google drive 

and 
https://pan.baidu.com/s/1qYlUyqK
as the BaiduYun link.

If you are in China , due to the GFW turn google unviable , then the BaiduYun link be the only option.

all the packed up executable files will be updated in the link:
<https://github.com/chinageology/GeoPython/blob/master/Download.md>

hope this can help.

BTW, the Harker diagram has a bug of failing to plot the second diagram, and I will fix it in the next version.

**Comment by cycleuser** [comment]
好吧，老兄好像你也是华人？我用中文简单回复一下哈：
打包好的可执行程序的下载地址都在https://github.com/chinageology/GeoPython/blob/master/Download.md 这个文件中更新。
目前Windows版本的下载链接是：
谷歌网盘：
https://drive.google.com/open?id=0B299gyAIgmpqWm5iS05PNXUwdjA
百度云盘：
https://pan.baidu.com/s/1qYlUyqK
由于我中华文明源远流长，由此上溯至六亿七千五百万年前，谷歌不能访问了，所以就推荐国内用户从百度云下载了。

注意这两个链接是一直更新的，所以还是推荐关注:https://github.com/chinageology/GeoPython/blob/master/Download.md
这里面的就会是最新版本的打包文件下载地址。

另外现在 Harker 图解有一个 Bug，就是每次打开程序后只能投图一次，第二次就空白了，这个我争取下一个版本修了它。

**Comment by Geokeke** [comment]
刚来 Github 不久，以为只能用英文 ：）
非常感谢！

**Comment by cycleuser** [comment]
哈哈，客气了客气了，都是自家人！我先 close 这个 issue了哈，如果后续遇到问题随时提出哈，我只要看到就会及时回复响应的哈。

**Comment by luqingxzb** [comment]
font{
        line-height: 1.5;
    }


    
谢谢于大胖！



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年04月20日 12:50，Freddy Yu<notifications@github.com> 写道： 


好吧，老兄好像你也是华人？我用中文简单回复一下哈：
打包好的可执行程序的下载地址都在https://github.com/chinageology/GeoPython/blob/master/Download.md 这个文件中更新。
目前Windows版本的下载链接是：
谷歌网盘：
https://drive.google.com/open?id=0B299gyAIgmpqWm5iS05PNXUwdjA
百度云盘：
https://pan.baidu.com/s/1qYlUyqK
由于我中华文明源远流长，由此上溯至六亿七千五百万年前，谷歌不能访问了，所以就推荐国内用户从百度云下载了。
注意这两个链接是一直更新的，所以还是推荐关注:https://github.com/chinageology/GeoPython/blob/master/Download.md
这里面的就会是最新版本的打包文件下载地址。
另外现在 Harker 图解有一个 Bug，就是每次打开程序后只能投图一次，第二次就空白了，这个我争取下一个版本修了它。
